'use client'
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import Head from 'next/head';
import AuthProvider from "@/provider/AuthProvider";
import { usePathname } from "next/navigation";
import { Toaster } from 'react-hot-toast';
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
const queryClient = new QueryClient()
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Ema-Enterprise",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  console.log(pathname)
  return (
    <html lang="en">
      <Head>
        <title>My Website Title</title>
        <meta name="title" content="Ema-Enterprise" />
        <meta name="description" content="My Next.js website description" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            {!pathname.startsWith('/admin-dashboard') && <Navbar />}
            <div className={`min-h-screen ${!pathname.startsWith('/admin-dashboard') && 'mt-10'}`}>
              {children}
            </div>
            <Footer />
          </AuthProvider>
          <Toaster position="top-center" />
        </QueryClientProvider>
      </body>
    </html >
  );
}
